### 查询当前用户已授权的主机分组及主机
GET {{baseUrl}}/asset/authorized-data/current-host-group
Authorization: {{token}}

### 查询当前用户已授权的主机秘钥
GET {{baseUrl}}/asset/authorized-data/current-host-key
Authorization: {{token}}

### 查询当前用户已授权的主机身份
GET {{baseUrl}}/asset/authorized-data/current-host-identity
Authorization: {{token}}

