### 创建计划任务
POST {{baseUrl}}/asset/exec-job/create
Content-Type: application/json
Authorization: {{token}}

{
  "name": "测试 1",
  "expression": "0 */3 * * * ?",
  "timeout": 0,
  "scriptExec": 0,
  "command": "echo 123",
  "parameterSchema": "[]",
  "hostIdList": [1]
}


### 更新计划任务
PUT {{baseUrl}}/asset/exec-job/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": 5,
  "name": "测试 1",
  "expression": "0 */10 * * * ?",
  "timeout": 0,
  "scriptExec": 0,
  "command": "echo 123",
  "parameterSchema": "[]",
  "hostIdList": [
    1
  ]
}


### 更新计划任务状态
PUT {{baseUrl}}/asset/exec-job/update-status
Content-Type: application/json
Authorization: {{token}}

{
  "id": 5,
  "status": 0
}


### 查询计划任务
GET {{baseUrl}}/asset/exec-job/get?id=1
Authorization: {{token}}


### 分页查询计划任务
POST {{baseUrl}}/asset/exec-job/query
Content-Type: application/json
Authorization: {{token}}

{
  "page": 1,
  "limit": 10,
  "id": "",
  "name": "",
  "command": "",
  "status": ""
}


### 删除计划任务
DELETE {{baseUrl}}/asset/exec-job/delete?id=1
Authorization: {{token}}


###
