### 批量执行命令
POST {{baseUrl}}/asset/exec/exec-command
Content-Type: application/json
Authorization: {{token}}

{
  "description": 1,
  "timeout": 10,
  "command": "echo 这是日志@{{ hostAddress }}\nsleep 1\necho @{{ hostName }}",
  "parameterSchema": "[]",
  "hostIdList": [1]
}


### 中断执行命令
POST {{baseUrl}}/asset/exec/interrupt-command
Content-Type: application/json
Authorization: {{token}}

{
  "logId": 7
}


### 查看执行日志
POST {{baseUrl}}/asset/exec/tail-log
Content-Type: application/json
Authorization: {{token}}

{
  "execId": 56
}


### 下载执行日志文件
GET {{baseUrl}}/asset/exec/download-log?id=83
Authorization: {{token}}


###
