### 批量执行命令
POST {{baseUrl}}/asset/exec-command/exec
Content-Type: application/json
Authorization: {{token}}

{
  "description": 1,
  "timeout": 10,
  "scriptExec": 0,
  "command": "echo 这是日志@{{ hostAddress }}\nsleep 1\necho @{{ hostName }}",
  "parameterSchema": "[]",
  "hostIdList": [1]
}

### 批量执行命令
POST {{baseUrl}}/asset/exec-command/re-exec
Content-Type: application/json
Authorization: {{token}}

{
  "logId": 1
}


###
