### 创建计划执行任务
POST {{baseUrl}}/asset/exec-job/create
Content-Type: application/json
Authorization: {{token}}

{
  "name": "",
  "expression": "",
  "timeout": "",
  "command": "",
  "parameterSchema": "",
  "status": "",
  "recentLogId": ""
}


### 更新计划执行任务
PUT {{baseUrl}}/asset/exec-job/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "name": "",
  "expression": "",
  "timeout": "",
  "command": "",
  "parameterSchema": "",
  "status": "",
  "recentLogId": ""
}


### 查询计划执行任务
GET {{baseUrl}}/asset/exec-job/get?id=1
Authorization: {{token}}


### 批量查询计划执行任务
GET {{baseUrl}}/asset/exec-job/batch-get?idList=1,2,3
Authorization: {{token}}


### 查询全部计划执行任务
POST {{baseUrl}}/asset/exec-job/list
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "name": "",
  "expression": "",
  "timeout": "",
  "command": "",
  "parameterSchema": "",
  "status": "",
  "recentLogId": ""
}


### 分页查询计划执行任务
POST {{baseUrl}}/asset/exec-job/query
Content-Type: application/json
Authorization: {{token}}

{
  "page": 1,
  "limit": 10,
  "id": "",
  "name": "",
  "expression": "",
  "timeout": "",
  "command": "",
  "parameterSchema": "",
  "status": "",
  "recentLogId": ""
}


### 删除计划执行任务
DELETE {{baseUrl}}/asset/exec-job/delete?id=1
Authorization: {{token}}


### 批量删除计划执行任务
DELETE {{baseUrl}}/asset/exec-job/batch-delete?idList=1,2,3
Authorization: {{token}}

###
