### 批量执行命令
POST {{baseUrl}}/asset/exec/exec-command
Content-Type: application/json
Authorization: {{token}}

{
  "description": 1,
  "timeout": 10,
  "command": "echo @{{ hostAddress }}\nsleep 10\necho @{{ str }}",
  "parameter": "{\"str\":\"end\"}",
  "hostIdList": [1,7]
}


### 中断执行命令
POST {{baseUrl}}/asset/exec/interrupt-command
Content-Type: application/json
Authorization: {{token}}

{
  "logId": 7
}


###
