### 创建主机分组
POST {{baseUrl}}/asset/host-group/create
Content-Type: application/json
Authorization: {{token}}

{
  "parentId": -1,
  "name": ""
}


### 查询主机分组
GET {{baseUrl}}/asset/host-group/tree
Authorization: {{token}}


### 修改名称
PUT {{baseUrl}}/asset/host-group/rename
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "name": ""
}


### 移动位置
PUT {{baseUrl}}/asset/host-group/move
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "targetId": "",
  "position": ""
}


### 删除主机分组
DELETE {{baseUrl}}/asset/host-group/delete?id=1
Authorization: {{token}}


### 获取已授权的分组
GET {{baseUrl}}/asset/host-group/get-authorized-group?userId=1
Authorization: {{token}}


### 主机分组授权
PUT {{baseUrl}}/asset/host-group/grant
Content-Type: application/json
Authorization: {{token}}

{
  "userId": 10,
  "groupIdList": [
    3,
    5
  ]
}

###
