### 创建上传任务
POST {{baseUrl}}/asset/upload-task/create
Content-Type: application/json
Authorization: {{token}}

{
  "remotePath": "/root/batch",
  "description": "",
  "hostIdList": [
    1,
    7,
    8
  ],
  "files": [
    {
      "fileId": "1",
      "filePath": "qr.txt",
      "fileSize": 3
    },
    {
      "fileId": "2",
      "filePath": "dir/key.txt",
      "fileSize": 3
    }
  ]
}


### 开始上传
POST {{baseUrl}}/asset/upload-task/start
Content-Type: application/json
Authorization: {{token}}

{
  "id": 1
}


### 查询上传任务
GET {{baseUrl}}/asset/upload-task/get?id=1
Authorization: {{token}}


### 分页查询上传任务
POST {{baseUrl}}/asset/upload-task/query
Content-Type: application/json
Authorization: {{token}}

{
  "page": 1,
  "limit": 10,
  "id": "",
  "userId": "",
  "description": "",
  "status": ""
}


### 删除上传任务
DELETE {{baseUrl}}/asset/upload-task/delete?id=1
Authorization: {{token}}


### 批量删除上传任务
DELETE {{baseUrl}}/asset/upload-task/batch-delete?idList=1,2,3
Authorization: {{token}}

###
