### 登录 - admin 用户
POST {{baseUrl}}/infra/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "21232f297a57a5a743894a0e4a801fc3"
}


### 登录
POST {{baseUrl}}/infra/auth/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}


### 登出
GET {{baseUrl}}/infra/auth/logout
Authorization: {{token}}
