### 创建字典配置项
POST {{baseUrl}}/infra/dict-key/create
Content-Type: application/json
Authorization: {{token}}

{
  "key": "",
  "valueType": "",
  "extraSchema": "",
  "desc": ""
}


### 更新字典配置项
PUT {{baseUrl}}/infra/dict-key/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "key": "",
  "valueType": "",
  "extraSchema": "",
  "desc": ""
}



### 查询全部字典配置项
POST {{baseUrl}}/infra/dict-key/list
Authorization: {{token}}


### 删除字典配置项
DELETE {{baseUrl}}/infra/dict-key/delete?id=1
Authorization: {{token}}


### 批量删除字典配置项
DELETE {{baseUrl}}/infra/dict-key/batch-delete?idList=1,2,3
Authorization: {{token}}


###
