### 创建字典配置值
POST {{baseUrl}}/infra/dict-value/create
Content-Type: application/json
Authorization: {{token}}

{
  "keyId": "",
  "key": "",
  "label": "",
  "value": "",
  "desc": "",
  "extra": "",
  "sort": ""
}


### 更新字典配置值
PUT {{baseUrl}}/infra/dict-value/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "keyId": "",
  "key": "",
  "label": "",
  "value": "",
  "desc": "",
  "extra": "",
  "sort": ""
}


### 查询全部字典配置值
POST {{baseUrl}}/infra/dict-value/list?key=
Authorization: {{token}}


### 分页查询字典配置值
POST {{baseUrl}}/infra/dict-value/query
Content-Type: application/json
Authorization: {{token}}

{
  "page": 1,
  "limit": 10,
  "keyId": "",
  "label": "",
  "value": "",
  "desc": ""
}


### 删除字典配置值
DELETE {{baseUrl}}/infra/dict-value/delete?id=1
Authorization: {{token}}


### 批量删除字典配置值
DELETE {{baseUrl}}/infra/dict-value/batch-delete?idList=1,2,3
Authorization: {{token}}


