### 查询当前用户信息
GET {{baseUrl}}/infra/mine/get-user
Authorization: {{token}}


### 更新当前用户信息
PUT {{baseUrl}}/infra/mine/update-user
Content-Type: application/json
Authorization: {{token}}

{
  "nickname": "名称",
  "mobile": "15555555555",
  "email": "123@123.com"
}


### 修改当前用户密码
PUT {{baseUrl}}/infra/mine/update-password
Content-Type: application/json
Authorization: {{token}}

{
  "beforePassword": "21232f297a57a5a743894a0e4a801fc3",
  "password": "21232f297a57a5a743894a0e4a801fc3"
}


### 查询当前用户登录日志
GET {{baseUrl}}/infra/mine/login-history
Authorization: {{token}}

###