### 分页查询操作日志
POST {{baseUrl}}/infra/operator-log/query
Content-Type: application/json
Authorization: {{token}}

{
  "page": 1,
  "limit": 10,
  "userId": "",
  "module": "",
  "type": "",
  "result": "",
  "startTime": "",
  "endTime": ""
}

### 查询登录日志
GET {{baseUrl}}/infra/operator-log/login-history?username=admin
Content-Type: application/json
Authorization: {{token}}

###