### 更新用户偏好-全部
PUT {{baseUrl}}/infra/preference/update
Content-Type: application/json
Authorization: {{token}}

{
  "type": "SYSTEM",
  "item": "",
  "value": ""
}


### 更新用户偏好-部分
PUT {{baseUrl}}/infra/preference/update-partial
Content-Type: application/json
Authorization: {{token}}

{
  "type": "SYSTEM",
  "config": {
  }
}


### 查询用户偏好
GET {{baseUrl}}/infra/preference/get?type=SYSTEM
Authorization: {{token}}

