### 创建角色菜单关联
POST {{baseUrl}}/infra/system-role-menu/create
Content-Type: application/json
Authorization: {{token}}

{
  "roleId": "",
  "menuId": ""
}


### 通过 id 更新角色菜单关联
PUT {{baseUrl}}/infra/system-role-menu/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "roleId": "",
  "menuId": ""
}


### 通过 id 查询角色菜单关联
GET {{baseUrl}}/infra/system-role-menu/get?id=1
Authorization: {{token}}


### 通过 id 批量查询角色菜单关联
GET {{baseUrl}}/infra/system-role-menu/list?idList=1,2,3
Authorization: {{token}}


### 分页查询角色菜单关联
POST {{baseUrl}}/infra/system-role-menu/query
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "roleId": "",
  "menuId": ""
}


### 通过 id 删除角色菜单关联
DELETE {{baseUrl}}/infra/system-role-menu/delete?id=1
Authorization: {{token}}


### 通过 id 批量删除角色菜单关联
DELETE {{baseUrl}}/infra/system-role-menu/delete-batch?idList=1,2,3
Authorization: {{token}}



