### 查询系统消息列表
POST {{baseUrl}}/infra/system-message/list
Content-Type: application/json
Authorization: {{token}}

{
  "limit": 10,
  "maxId": null,
  "classify": "NOTICE",
  "queryCount": true,
  "queryUnread": true
}


### 查询是否有未读消息
GET {{baseUrl}}/infra/system-message/has-unread
Authorization: {{token}}


### 查询是否有未读消息
PUT {{baseUrl}}/infra/system-message/read?id=1
Authorization: {{token}}


### 更新全部系统消息为已读
PUT {{baseUrl}}/infra/system-message/read-all?classify=NOTICE
Authorization: {{token}}


### 删除系统消息
DELETE {{baseUrl}}/infra/system-message/delete?id=1
Authorization: {{token}}


### 清理已读的系统消息
DELETE {{baseUrl}}/infra/system-message/clear?classify=NOTICE
Authorization: {{token}}

###
