### 创建菜单
POST {{baseUrl}}/infra/system-menu/create
Content-Type: application/json
Authorization: {{token}}

{
  "parentId": "",
  "name": "",
  "permission": "",
  "type": "",
  "sort": "",
  "status": "",
  "cache": "",
  "icon": "",
  "path": "",
  "component": ""
}


### 通过 id 更新菜单
PUT {{baseUrl}}/infra/system-menu/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "parentId": "",
  "name": "",
  "permission": "",
  "type": "",
  "sort": "",
  "status": "",
  "cache": "",
  "icon": "",
  "path": "",
  "component": ""
}


### 通过 id 查询菜单
GET {{baseUrl}}/infra/system-menu/get?id=1
Authorization: {{token}}


### 通过 id 批量查询菜单
GET {{baseUrl}}/infra/system-menu/list?idList=1,2,3
Authorization: {{token}}


### 分页查询菜单
POST {{baseUrl}}/infra/system-menu/query
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "parentId": "",
  "name": "",
  "permission": "",
  "type": "",
  "sort": "",
  "status": "",
  "cache": "",
  "icon": "",
  "path": "",
  "component": ""
}


### 通过 id 删除菜单
DELETE {{baseUrl}}/infra/system-menu/delete?id=1
Authorization: {{token}}


### 通过 id 批量删除菜单
DELETE {{baseUrl}}/infra/system-menu/delete-batch?idList=1,2,3
Authorization: {{token}}



