### 创建命令片段
POST {{baseUrl}}/asset/command-snippet/create
Content-Type: application/json
Authorization: {{token}}

{
  "groupId": "",
  "name": "",
  "command": ""
}


### 更新命令片段
PUT {{baseUrl}}/asset/command-snippet/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "groupId": "",
  "name": "",
  "command": ""
}


### 查询全部命令片段
GET {{baseUrl}}/asset/command-snippet/list
Authorization: {{token}}


### 删除命令片段
DELETE {{baseUrl}}/asset/command-snippet/delete?id=1
Authorization: {{token}}


###
