### 查询主机配置
GET {{baseUrl}}/asset/host-config/get?hostId=1&type=SSH
Authorization: {{token}}

### 查询全部主机配置
GET {{baseUrl}}/asset/host-config/list?hostId=1
Authorization: {{token}}

### 通过 id 更新主机配置
PUT {{baseUrl}}/asset/host-config/update
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "config": "",
  "version": ""
}

### 通过 id 更新主机配置状态
PUT {{baseUrl}}/asset/host-config/update-status
Content-Type: application/json
Authorization: {{token}}

{
  "id": "",
  "status": "",
  "version": ""
}

###
