### 获取主机拓展信息
GET {{baseUrl}}/asset/host-extra/get?hostId=1&item=ssh
Authorization: {{token}}

### 获取多个主机拓展信息
POST {{baseUrl}}/asset/host-extra/list
Content-Type: application/json
Authorization: {{token}}

{
  "hostId": 1,
  "items": [
    "ssh"
  ]
}

### 修改主机拓展信息
PUT {{baseUrl}}/asset/host-extra/update
Content-Type: application/json
Authorization: {{token}}

{
  "hostId": 1,
  "item": "ssh",
  "extra": "{\"authType\":\"DEFAULT\"}"
}

###
